export const HOMEUPDATE = "HOMEUPDATE";
export const STEREOTYPEUPDATE = "STEREOTYPEUPDATE";
export const SPECIALTYUPDATE = "SPECIALTYUPDATE";
export const UPDATELOGIN = "UPDATELOGIN";
export const PASSVERIFICATION = 'PASSVERIFICATION';
export const FAILVERIFICATION = 'FAILVERIFICATION';
